version: '3.8'

services:
  test_parse_weather_redis:
    container_name: test_parse_weather
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEST_TYPE_CACHE=REDIS
      - TEST_REDIS_HOST=test_redis
      - TEST_REDIS_PORT=630
    volumes:
      - test_parse_weather:/home/code/logs
    command: poetry run python -m pytest --cov=src tests/
    networks:
      - test_everyday_bot
    depends_on:
      test_redis:
        condition: service_healthy

  test_redis:
    container_name: test_redis
    image: redis:latest
    command: --port 6300
    ports:
      - 6300:6300
    networks:
      - test_everyday_bot
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6300", "ping"]
      interval: 1s
      timeout: 1s
      retries: 5

networks:
  test_everyday_bot:

volumes:
  test_parse_weather:
