version: '3.8'

services:
  test_parse_weather_redis:
    container_name: test_parse_weather
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEST_TYPE_CACHE=DICT
    volumes:
      - test_parse_weather:/home/code/logs
    command: poetry run python -m pytest --cov=src tests/
    networks:
      - test_everyday_bot

networks:
  test_everyday_bot:

volumes:
  test_parse_weather:
