version: '3.8'

services:
  test_parse_weather_dict:
    container_name: test_parse_weather
    env_file:
      - config/.env.test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - test_parse_weather:/home/code/logs
    command: poetry run python -m pytest --cov=src tests/

volumes:
  test_parse_weather:
